version: '3'

networks:
    nginx-php74-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - db
        networks:
            - nginx-php74-mysql8-node

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php74-mysql8-node

    # mysql
   # mysql8-service:
   #     image: mysql:8
   #     container_name: mysql8-container
   #     ports:
   #        - "3306:3306"
    #    volumes:
   #         - ./mysql:/var/lib/mysql
   #     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   #     restart: always # always restart unless stopped manually
    #    environment:
   #         MYSQL_ROOT_PASSWORD: secret
    ##        MYSQL_PASSWORD: "!ChangeMe!"
    #        MYSQL_USER: app
    #    networks:
    #        - nginx-php74-mysql8-node
    db:
        image: postgres:14.1-alpine
        container_name: db
        restart: always
        environment:
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=!ChangeMe!
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - nginx-php74-mysql8-node
            
    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php74-mysql8-node
volumes:
    db:
        driver: local
